### ISSUE TITLE
What does `v` mean?

### ISSUE THREAD

**Issue by Sciroccogti** [Higuoxing/seu-wlan#2]
https://github.com/higuoxing/seu-wlan/blob/c24164f09e4d01194459252a3331af873174a477/seu-wlan#L114

**Comment by higuoxing** [comment]
时代久远，我也不清楚了，这个是抓包得到的。:)

**Comment by higuoxing** [comment]
还有个很有趣的事情，那个登出接口没做鉴权，也就是说可以踢别人下线 ...

https://gist.github.com/higuoxing/8e603de3654de285210045f4b35e5130

**Comment by Sciroccogti** [comment]
> 还有个很有趣的事情，那个登出接口没做鉴权，也就是说可以踢别人下线 ...
> 
> https://gist.github.com/higuoxing/8e603de3654de285210045f4b35e5130

啊这，我以为还得先知道对应 IP 或者 MAC 呢。。
